### ISSUE TITLE
Issue Creating Timeline

### ISSUE THREAD

**Issue by ChaseFloydInc** [CodyHouse/horizontal-timeline#14] opened 2019-08-14 12:36 UTC
Hi!

I created the corresponding folders and added all of the files from "assets" into them.

I then pasted your index.html onto one of my pages, but the timeline did not work.

It also changed the css style of my page.

I want to just add in this timeline onto my own page as if it were an embedded html. Can you help me do this?

**Comment by claudia-romano** [comment] 2019-08-15 08:16
Hi @ChaseFloydInc,
unfortunately, it's impossible for us to help you integrate our resources in your code, or check for bugs when our resources are part of a complex project. 

I'm closing this issue since there's not a bug with the experiment. In case you find one, feel free to open a new issue. Cheers.

**Closed as completed by claudia-romano** 2019-08-15 08:16 UTC
